add

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,3 +43,15 @@ jobs:
       run: |
         docker push ${{ secrets.DOCKER_USERNAME }}/pos-sytem-usecase:${{ env.TAG }}
         docker push ${{ secrets.DOCKER_USERNAME }}/pos-sytem-usecase:${{ env.LATEST_TAG }}
+
+    # Step 6: Tricy Scan Images
+    - name: Run Trivy Scan
+      run: |
+        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
+        ./trivy image ${{ secrets.DOCKER_USERNAME }}/pos-sytem-usecase:${{ env.LATEST_TAG }} &&
+        CRITICAL_COUNT=$(trivy image --severity CRITICAL --no-progress --format json ${{ secrets.DOCKER_USERNAME }}/pos-sytem-usecase:${{ env.LATEST_TAG }} | jq '.Results[].Vulnerabilities[] | select(.Severity=="CRITICAL")' | wc -l)
+        echo "Critical vulnerabilities found: $CRITICAL_COUNT"
+        if [ "$CRITICAL_COUNT" -gt 10 ]; then
+          echo "More than 10 critical vulnerabilities detected. Failing the build."
+          exit 1
+        fi
